[package]
name = "deemak"
version = "0.1.0"
edition = "2024"

[dependencies]
raylib = "5.5.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
rocket = { version = "0.5.1", features = ["json"] }
