pub mod find_root;
mod tests;
pub use find_root::relative_deemak_path;
pub mod log;
pub use log::debug_mode;
pub mod auth;
pub mod cleanup;
pub mod config;
pub mod globals;
pub mod prompt;
pub mod shell_history;
pub mod tab_completion;
pub mod test_utils;
pub mod wrapit;
